---
- name: Configure postgresql.conf for replication
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
  notify: Restart PostgreSQL

- name: Configure pg_hba.conf for replication access
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
  notify: Reload PostgreSQL

- name: Restart PostgreSQL to apply changes
  service:
    name: postgresql@16-main
    state: restarted

- name: Create replication user
  become_user: postgres
  postgresql_user:
    name: replication_user
    password: strongpassword1
    role_attr_flags: "REPLICATION"
    state: present

- name: Create test database
  become_user: postgres
  postgresql_db:
    name: librarysystem
    state: present

- name: Ensure authors table exists
  become_user: postgres
  postgresql_query:
    db: librarysystem
    query: |
      CREATE TABLE IF NOT EXISTS authors (
          author_id SERIAL PRIMARY KEY,
          first_name VARCHAR(50) NOT NULL,
          last_name VARCHAR(50) NOT NULL,
          birth_date DATE
      );
  ignore_errors: no

- name: Create a publication for logical replication
  become_user: postgres
  postgresql_query:
    db: librarysystem
    query: "CREATE PUBLICATION library_pub FOR TABLE authors;"
  ignore_errors: no
