---
# Оновлення кешу пакетів APT, щоб отримати останню інформацію про доступні пакети
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Встановлення PostgreSQL та всіх необхідних залежностей
- name: Install PostgreSQL and required dependencies
  apt:
    name:
      - postgresql  # Основний сервер PostgreSQL
      - postgresql-contrib  # Додаткові утиліти для PostgreSQL
      - python3-psycopg2  # Бібліотека для Ansible для підключення до PostgreSQL
      - libpq-dev  # Драйвер PostgreSQL для компіляції залежностей
      - acl  # Дозволяє Ansible використовувати команду `become_user`
    state: present

# Перевірка, що служба PostgreSQL працює і запускається при завантаженні сервера
- name: Ensure PostgreSQL service is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes
  register: pg_service_status

# Отримання версії встановленого PostgreSQL
- name: Get PostgreSQL version
  shell: "psql --version | awk '{print $3}' | cut -d. -f1"
  register: pg_version
  changed_when: false

# Перевірка стану служби PostgreSQL
- name: Check PostgreSQL service status
  service:
    name: postgresql
    state: started
  register: pg_service_status

# Виведення статусу служби і версії PostgreSQL
- name: Display PostgreSQL service status and version
  debug:
    msg:
      - "PostgreSQL service is {{ 'running' if pg_service_status.state == 'started' else 'not running' }}"
      - "Installed PostgreSQL version: {{ pg_version.stdout }}"