---
- name: Ensure replication slot exists
  become_user: postgres
  postgresql_query:
    db: postgres
    query: "SELECT * FROM pg_create_physical_replication_slot('replication_slot');"
  ignore_errors: yes

- name: Enable replication on primary server
  become_user: postgres
  postgresql_query:
    db: postgres
    query: "ALTER SYSTEM SET wal_level = 'logical';"
  notify: Restart PostgreSQL

- name: Configure streaming replication on replica
  become_user: postgres
  postgresql_query:
    db: postgres
    query: "ALTER SYSTEM SET max_wal_senders = 10;"
  notify: Restart PostgreSQL

- name: Allow replication connections in pg_hba.conf
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    line: "host replication {{ replication_user }} {{ replica_server_ip }}/32 md5"
    state: present
  notify: Reload PostgreSQL
